log stderr all;
router id 5.5.5.5;
protocol device {}
protocol direct { ipv4; }
protocol kernel { ipv4 { export all; }; }
protocol rip rip1 {
    ipv4 { import all; export all; };
    interface "eth0" { mode broadcast; version 2; };
    interface "eth1" { mode broadcast; version 2; };
}
