log stderr all;
router id 1.1.1.1;
protocol device {}
protocol direct { ipv4; }
protocol kernel { ipv4 { export all; }; }
protocol bgp bgp_r2 {
    local 10.12.0.10 as 100;
    neighbor 10.12.0.20 as 100;
    ipv4 { import all; export all; };
}
protocol bgp bgp_r5 {
    local 10.15.0.10 as 100;
    neighbor 10.15.0.50 as 300;
    ipv4 { import all; export all; };
}
