log stderr all;
router id 2.2.2.2;
protocol device {}
protocol direct { ipv4; }
protocol kernel { ipv4 { export all; }; }
protocol bgp bgp_r1 {
    local 10.12.0.20 as 100;
    neighbor 10.12.0.10 as 100;
    ipv4 { import all; export all; };
}
protocol bgp bgp_r3 {
    local 10.23.0.20 as 100;
    neighbor 10.23.0.30 as 200;
    ipv4 { import all; export all; };
}
protocol bgp bgp_r4 {
    local 10.24.0.20 as 100;
    neighbor 10.24.0.40 as 200;
    ipv4 { import all; export all; };
}
