log stderr all;
router id 3.3.3.3;
protocol device {}
protocol direct { ipv4; }
protocol kernel { ipv4 { export all; }; }
protocol bgp bgp_r2 {
    local 10.23.0.30 as 200;
    neighbor 10.23.0.20 as 100;
    ipv4 { import all; export all; };
}
protocol bgp bgp_r5 {
    local 10.35.0.30 as 200;
    neighbor 10.35.0.50 as 300;
    ipv4 { import all; export all; };
}
