log stderr all;
router id 4.4.4.4;
protocol device {}
protocol direct { ipv4; }
protocol kernel { ipv4 { export all; }; }
protocol bgp bgp_r2 {
    local 10.24.0.40 as 200;
    neighbor 10.24.0.20 as 100;
    ipv4 { import all; export all; };
}
