log stderr all;
router id 5.5.5.5;
protocol device {}
protocol direct { ipv4; }
protocol kernel { ipv4 { export all; }; }
protocol bgp bgp_r1 {
    local 10.15.0.50 as 300;
    neighbor 10.15.0.10 as 100;
    ipv4 { import all; export all; };
}
protocol bgp bgp_r3 {
    local 10.35.0.50 as 300;
    neighbor 10.35.0.30 as 200;
    ipv4 { import all; export all; };
}
